// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fileaudit.proto

package com.grpc.resources;

/**
 * Protobuf type {@code FileDetailsRequest}
 */
public  final class FileDetailsRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:FileDetailsRequest)
    FileDetailsRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FileDetailsRequest.newBuilder() to construct.
  private FileDetailsRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FileDetailsRequest() {
    identifier_ = "";
    fileSizeInBytes_ = "";
    nfsUserId_ = "";
    nfsGroupId_ = "";
    filePermission_ = "";
    mTime_ = "";
    aTIme_ = "";
    fileFormat_ = "";
    creationTime_ = "";
    auditedOn_ = "";
    fileResearchHash_ = "";
    currentParty_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new FileDetailsRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FileDetailsRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            identifier_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            fileSizeInBytes_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            nfsUserId_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            nfsGroupId_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            filePermission_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            mTime_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            aTIme_ = s;
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            fileFormat_ = s;
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();

            creationTime_ = s;
            break;
          }
          case 82: {
            java.lang.String s = input.readStringRequireUtf8();

            auditedOn_ = s;
            break;
          }
          case 90: {
            java.lang.String s = input.readStringRequireUtf8();

            fileResearchHash_ = s;
            break;
          }
          case 98: {
            java.lang.String s = input.readStringRequireUtf8();

            currentParty_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.grpc.resources.Fileaudit.internal_static_FileDetailsRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.grpc.resources.Fileaudit.internal_static_FileDetailsRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.grpc.resources.FileDetailsRequest.class, com.grpc.resources.FileDetailsRequest.Builder.class);
  }

  public static final int IDENTIFIER_FIELD_NUMBER = 1;
  private volatile java.lang.Object identifier_;
  /**
   * <code>string identifier = 1;</code>
   * @return The identifier.
   */
  public java.lang.String getIdentifier() {
    java.lang.Object ref = identifier_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      identifier_ = s;
      return s;
    }
  }
  /**
   * <code>string identifier = 1;</code>
   * @return The bytes for identifier.
   */
  public com.google.protobuf.ByteString
      getIdentifierBytes() {
    java.lang.Object ref = identifier_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      identifier_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FILESIZEINBYTES_FIELD_NUMBER = 2;
  private volatile java.lang.Object fileSizeInBytes_;
  /**
   * <code>string fileSizeInBytes = 2;</code>
   * @return The fileSizeInBytes.
   */
  public java.lang.String getFileSizeInBytes() {
    java.lang.Object ref = fileSizeInBytes_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      fileSizeInBytes_ = s;
      return s;
    }
  }
  /**
   * <code>string fileSizeInBytes = 2;</code>
   * @return The bytes for fileSizeInBytes.
   */
  public com.google.protobuf.ByteString
      getFileSizeInBytesBytes() {
    java.lang.Object ref = fileSizeInBytes_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      fileSizeInBytes_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NFSUSERID_FIELD_NUMBER = 3;
  private volatile java.lang.Object nfsUserId_;
  /**
   * <code>string nfsUserId = 3;</code>
   * @return The nfsUserId.
   */
  public java.lang.String getNfsUserId() {
    java.lang.Object ref = nfsUserId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      nfsUserId_ = s;
      return s;
    }
  }
  /**
   * <code>string nfsUserId = 3;</code>
   * @return The bytes for nfsUserId.
   */
  public com.google.protobuf.ByteString
      getNfsUserIdBytes() {
    java.lang.Object ref = nfsUserId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      nfsUserId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NFSGROUPID_FIELD_NUMBER = 4;
  private volatile java.lang.Object nfsGroupId_;
  /**
   * <code>string nfsGroupId = 4;</code>
   * @return The nfsGroupId.
   */
  public java.lang.String getNfsGroupId() {
    java.lang.Object ref = nfsGroupId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      nfsGroupId_ = s;
      return s;
    }
  }
  /**
   * <code>string nfsGroupId = 4;</code>
   * @return The bytes for nfsGroupId.
   */
  public com.google.protobuf.ByteString
      getNfsGroupIdBytes() {
    java.lang.Object ref = nfsGroupId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      nfsGroupId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FILEPERMISSION_FIELD_NUMBER = 5;
  private volatile java.lang.Object filePermission_;
  /**
   * <code>string filePermission = 5;</code>
   * @return The filePermission.
   */
  public java.lang.String getFilePermission() {
    java.lang.Object ref = filePermission_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      filePermission_ = s;
      return s;
    }
  }
  /**
   * <code>string filePermission = 5;</code>
   * @return The bytes for filePermission.
   */
  public com.google.protobuf.ByteString
      getFilePermissionBytes() {
    java.lang.Object ref = filePermission_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      filePermission_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MTIME_FIELD_NUMBER = 6;
  private volatile java.lang.Object mTime_;
  /**
   * <code>string mTime = 6;</code>
   * @return The mTime.
   */
  public java.lang.String getMTime() {
    java.lang.Object ref = mTime_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      mTime_ = s;
      return s;
    }
  }
  /**
   * <code>string mTime = 6;</code>
   * @return The bytes for mTime.
   */
  public com.google.protobuf.ByteString
      getMTimeBytes() {
    java.lang.Object ref = mTime_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      mTime_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ATIME_FIELD_NUMBER = 7;
  private volatile java.lang.Object aTIme_;
  /**
   * <code>string aTIme = 7;</code>
   * @return The aTIme.
   */
  public java.lang.String getATIme() {
    java.lang.Object ref = aTIme_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      aTIme_ = s;
      return s;
    }
  }
  /**
   * <code>string aTIme = 7;</code>
   * @return The bytes for aTIme.
   */
  public com.google.protobuf.ByteString
      getATImeBytes() {
    java.lang.Object ref = aTIme_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      aTIme_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FILEFORMAT_FIELD_NUMBER = 8;
  private volatile java.lang.Object fileFormat_;
  /**
   * <code>string FileFormat = 8;</code>
   * @return The fileFormat.
   */
  public java.lang.String getFileFormat() {
    java.lang.Object ref = fileFormat_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      fileFormat_ = s;
      return s;
    }
  }
  /**
   * <code>string FileFormat = 8;</code>
   * @return The bytes for fileFormat.
   */
  public com.google.protobuf.ByteString
      getFileFormatBytes() {
    java.lang.Object ref = fileFormat_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      fileFormat_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CREATIONTIME_FIELD_NUMBER = 9;
  private volatile java.lang.Object creationTime_;
  /**
   * <code>string creationTime = 9;</code>
   * @return The creationTime.
   */
  public java.lang.String getCreationTime() {
    java.lang.Object ref = creationTime_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      creationTime_ = s;
      return s;
    }
  }
  /**
   * <code>string creationTime = 9;</code>
   * @return The bytes for creationTime.
   */
  public com.google.protobuf.ByteString
      getCreationTimeBytes() {
    java.lang.Object ref = creationTime_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      creationTime_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AUDITEDON_FIELD_NUMBER = 10;
  private volatile java.lang.Object auditedOn_;
  /**
   * <code>string auditedOn = 10;</code>
   * @return The auditedOn.
   */
  public java.lang.String getAuditedOn() {
    java.lang.Object ref = auditedOn_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      auditedOn_ = s;
      return s;
    }
  }
  /**
   * <code>string auditedOn = 10;</code>
   * @return The bytes for auditedOn.
   */
  public com.google.protobuf.ByteString
      getAuditedOnBytes() {
    java.lang.Object ref = auditedOn_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      auditedOn_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FILERESEARCHHASH_FIELD_NUMBER = 11;
  private volatile java.lang.Object fileResearchHash_;
  /**
   * <code>string fileResearchHash = 11;</code>
   * @return The fileResearchHash.
   */
  public java.lang.String getFileResearchHash() {
    java.lang.Object ref = fileResearchHash_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      fileResearchHash_ = s;
      return s;
    }
  }
  /**
   * <code>string fileResearchHash = 11;</code>
   * @return The bytes for fileResearchHash.
   */
  public com.google.protobuf.ByteString
      getFileResearchHashBytes() {
    java.lang.Object ref = fileResearchHash_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      fileResearchHash_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CURRENTPARTY_FIELD_NUMBER = 12;
  private volatile java.lang.Object currentParty_;
  /**
   * <code>string currentParty = 12;</code>
   * @return The currentParty.
   */
  public java.lang.String getCurrentParty() {
    java.lang.Object ref = currentParty_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      currentParty_ = s;
      return s;
    }
  }
  /**
   * <code>string currentParty = 12;</code>
   * @return The bytes for currentParty.
   */
  public com.google.protobuf.ByteString
      getCurrentPartyBytes() {
    java.lang.Object ref = currentParty_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      currentParty_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getIdentifierBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, identifier_);
    }
    if (!getFileSizeInBytesBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, fileSizeInBytes_);
    }
    if (!getNfsUserIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, nfsUserId_);
    }
    if (!getNfsGroupIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, nfsGroupId_);
    }
    if (!getFilePermissionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, filePermission_);
    }
    if (!getMTimeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, mTime_);
    }
    if (!getATImeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, aTIme_);
    }
    if (!getFileFormatBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, fileFormat_);
    }
    if (!getCreationTimeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, creationTime_);
    }
    if (!getAuditedOnBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, auditedOn_);
    }
    if (!getFileResearchHashBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, fileResearchHash_);
    }
    if (!getCurrentPartyBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 12, currentParty_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getIdentifierBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, identifier_);
    }
    if (!getFileSizeInBytesBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, fileSizeInBytes_);
    }
    if (!getNfsUserIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, nfsUserId_);
    }
    if (!getNfsGroupIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, nfsGroupId_);
    }
    if (!getFilePermissionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, filePermission_);
    }
    if (!getMTimeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, mTime_);
    }
    if (!getATImeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, aTIme_);
    }
    if (!getFileFormatBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, fileFormat_);
    }
    if (!getCreationTimeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, creationTime_);
    }
    if (!getAuditedOnBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, auditedOn_);
    }
    if (!getFileResearchHashBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, fileResearchHash_);
    }
    if (!getCurrentPartyBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, currentParty_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.grpc.resources.FileDetailsRequest)) {
      return super.equals(obj);
    }
    com.grpc.resources.FileDetailsRequest other = (com.grpc.resources.FileDetailsRequest) obj;

    if (!getIdentifier()
        .equals(other.getIdentifier())) return false;
    if (!getFileSizeInBytes()
        .equals(other.getFileSizeInBytes())) return false;
    if (!getNfsUserId()
        .equals(other.getNfsUserId())) return false;
    if (!getNfsGroupId()
        .equals(other.getNfsGroupId())) return false;
    if (!getFilePermission()
        .equals(other.getFilePermission())) return false;
    if (!getMTime()
        .equals(other.getMTime())) return false;
    if (!getATIme()
        .equals(other.getATIme())) return false;
    if (!getFileFormat()
        .equals(other.getFileFormat())) return false;
    if (!getCreationTime()
        .equals(other.getCreationTime())) return false;
    if (!getAuditedOn()
        .equals(other.getAuditedOn())) return false;
    if (!getFileResearchHash()
        .equals(other.getFileResearchHash())) return false;
    if (!getCurrentParty()
        .equals(other.getCurrentParty())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + IDENTIFIER_FIELD_NUMBER;
    hash = (53 * hash) + getIdentifier().hashCode();
    hash = (37 * hash) + FILESIZEINBYTES_FIELD_NUMBER;
    hash = (53 * hash) + getFileSizeInBytes().hashCode();
    hash = (37 * hash) + NFSUSERID_FIELD_NUMBER;
    hash = (53 * hash) + getNfsUserId().hashCode();
    hash = (37 * hash) + NFSGROUPID_FIELD_NUMBER;
    hash = (53 * hash) + getNfsGroupId().hashCode();
    hash = (37 * hash) + FILEPERMISSION_FIELD_NUMBER;
    hash = (53 * hash) + getFilePermission().hashCode();
    hash = (37 * hash) + MTIME_FIELD_NUMBER;
    hash = (53 * hash) + getMTime().hashCode();
    hash = (37 * hash) + ATIME_FIELD_NUMBER;
    hash = (53 * hash) + getATIme().hashCode();
    hash = (37 * hash) + FILEFORMAT_FIELD_NUMBER;
    hash = (53 * hash) + getFileFormat().hashCode();
    hash = (37 * hash) + CREATIONTIME_FIELD_NUMBER;
    hash = (53 * hash) + getCreationTime().hashCode();
    hash = (37 * hash) + AUDITEDON_FIELD_NUMBER;
    hash = (53 * hash) + getAuditedOn().hashCode();
    hash = (37 * hash) + FILERESEARCHHASH_FIELD_NUMBER;
    hash = (53 * hash) + getFileResearchHash().hashCode();
    hash = (37 * hash) + CURRENTPARTY_FIELD_NUMBER;
    hash = (53 * hash) + getCurrentParty().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.grpc.resources.FileDetailsRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.grpc.resources.FileDetailsRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.grpc.resources.FileDetailsRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.grpc.resources.FileDetailsRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.grpc.resources.FileDetailsRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.grpc.resources.FileDetailsRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.grpc.resources.FileDetailsRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.grpc.resources.FileDetailsRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.grpc.resources.FileDetailsRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.grpc.resources.FileDetailsRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.grpc.resources.FileDetailsRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.grpc.resources.FileDetailsRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.grpc.resources.FileDetailsRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code FileDetailsRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:FileDetailsRequest)
      com.grpc.resources.FileDetailsRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.grpc.resources.Fileaudit.internal_static_FileDetailsRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.grpc.resources.Fileaudit.internal_static_FileDetailsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.grpc.resources.FileDetailsRequest.class, com.grpc.resources.FileDetailsRequest.Builder.class);
    }

    // Construct using com.grpc.resources.FileDetailsRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      identifier_ = "";

      fileSizeInBytes_ = "";

      nfsUserId_ = "";

      nfsGroupId_ = "";

      filePermission_ = "";

      mTime_ = "";

      aTIme_ = "";

      fileFormat_ = "";

      creationTime_ = "";

      auditedOn_ = "";

      fileResearchHash_ = "";

      currentParty_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.grpc.resources.Fileaudit.internal_static_FileDetailsRequest_descriptor;
    }

    @java.lang.Override
    public com.grpc.resources.FileDetailsRequest getDefaultInstanceForType() {
      return com.grpc.resources.FileDetailsRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.grpc.resources.FileDetailsRequest build() {
      com.grpc.resources.FileDetailsRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.grpc.resources.FileDetailsRequest buildPartial() {
      com.grpc.resources.FileDetailsRequest result = new com.grpc.resources.FileDetailsRequest(this);
      result.identifier_ = identifier_;
      result.fileSizeInBytes_ = fileSizeInBytes_;
      result.nfsUserId_ = nfsUserId_;
      result.nfsGroupId_ = nfsGroupId_;
      result.filePermission_ = filePermission_;
      result.mTime_ = mTime_;
      result.aTIme_ = aTIme_;
      result.fileFormat_ = fileFormat_;
      result.creationTime_ = creationTime_;
      result.auditedOn_ = auditedOn_;
      result.fileResearchHash_ = fileResearchHash_;
      result.currentParty_ = currentParty_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.grpc.resources.FileDetailsRequest) {
        return mergeFrom((com.grpc.resources.FileDetailsRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.grpc.resources.FileDetailsRequest other) {
      if (other == com.grpc.resources.FileDetailsRequest.getDefaultInstance()) return this;
      if (!other.getIdentifier().isEmpty()) {
        identifier_ = other.identifier_;
        onChanged();
      }
      if (!other.getFileSizeInBytes().isEmpty()) {
        fileSizeInBytes_ = other.fileSizeInBytes_;
        onChanged();
      }
      if (!other.getNfsUserId().isEmpty()) {
        nfsUserId_ = other.nfsUserId_;
        onChanged();
      }
      if (!other.getNfsGroupId().isEmpty()) {
        nfsGroupId_ = other.nfsGroupId_;
        onChanged();
      }
      if (!other.getFilePermission().isEmpty()) {
        filePermission_ = other.filePermission_;
        onChanged();
      }
      if (!other.getMTime().isEmpty()) {
        mTime_ = other.mTime_;
        onChanged();
      }
      if (!other.getATIme().isEmpty()) {
        aTIme_ = other.aTIme_;
        onChanged();
      }
      if (!other.getFileFormat().isEmpty()) {
        fileFormat_ = other.fileFormat_;
        onChanged();
      }
      if (!other.getCreationTime().isEmpty()) {
        creationTime_ = other.creationTime_;
        onChanged();
      }
      if (!other.getAuditedOn().isEmpty()) {
        auditedOn_ = other.auditedOn_;
        onChanged();
      }
      if (!other.getFileResearchHash().isEmpty()) {
        fileResearchHash_ = other.fileResearchHash_;
        onChanged();
      }
      if (!other.getCurrentParty().isEmpty()) {
        currentParty_ = other.currentParty_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.grpc.resources.FileDetailsRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.grpc.resources.FileDetailsRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object identifier_ = "";
    /**
     * <code>string identifier = 1;</code>
     * @return The identifier.
     */
    public java.lang.String getIdentifier() {
      java.lang.Object ref = identifier_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        identifier_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string identifier = 1;</code>
     * @return The bytes for identifier.
     */
    public com.google.protobuf.ByteString
        getIdentifierBytes() {
      java.lang.Object ref = identifier_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        identifier_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string identifier = 1;</code>
     * @param value The identifier to set.
     * @return This builder for chaining.
     */
    public Builder setIdentifier(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      identifier_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string identifier = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearIdentifier() {
      
      identifier_ = getDefaultInstance().getIdentifier();
      onChanged();
      return this;
    }
    /**
     * <code>string identifier = 1;</code>
     * @param value The bytes for identifier to set.
     * @return This builder for chaining.
     */
    public Builder setIdentifierBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      identifier_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object fileSizeInBytes_ = "";
    /**
     * <code>string fileSizeInBytes = 2;</code>
     * @return The fileSizeInBytes.
     */
    public java.lang.String getFileSizeInBytes() {
      java.lang.Object ref = fileSizeInBytes_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fileSizeInBytes_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string fileSizeInBytes = 2;</code>
     * @return The bytes for fileSizeInBytes.
     */
    public com.google.protobuf.ByteString
        getFileSizeInBytesBytes() {
      java.lang.Object ref = fileSizeInBytes_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fileSizeInBytes_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string fileSizeInBytes = 2;</code>
     * @param value The fileSizeInBytes to set.
     * @return This builder for chaining.
     */
    public Builder setFileSizeInBytes(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      fileSizeInBytes_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string fileSizeInBytes = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearFileSizeInBytes() {
      
      fileSizeInBytes_ = getDefaultInstance().getFileSizeInBytes();
      onChanged();
      return this;
    }
    /**
     * <code>string fileSizeInBytes = 2;</code>
     * @param value The bytes for fileSizeInBytes to set.
     * @return This builder for chaining.
     */
    public Builder setFileSizeInBytesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      fileSizeInBytes_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object nfsUserId_ = "";
    /**
     * <code>string nfsUserId = 3;</code>
     * @return The nfsUserId.
     */
    public java.lang.String getNfsUserId() {
      java.lang.Object ref = nfsUserId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nfsUserId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string nfsUserId = 3;</code>
     * @return The bytes for nfsUserId.
     */
    public com.google.protobuf.ByteString
        getNfsUserIdBytes() {
      java.lang.Object ref = nfsUserId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nfsUserId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string nfsUserId = 3;</code>
     * @param value The nfsUserId to set.
     * @return This builder for chaining.
     */
    public Builder setNfsUserId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      nfsUserId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string nfsUserId = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearNfsUserId() {
      
      nfsUserId_ = getDefaultInstance().getNfsUserId();
      onChanged();
      return this;
    }
    /**
     * <code>string nfsUserId = 3;</code>
     * @param value The bytes for nfsUserId to set.
     * @return This builder for chaining.
     */
    public Builder setNfsUserIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      nfsUserId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object nfsGroupId_ = "";
    /**
     * <code>string nfsGroupId = 4;</code>
     * @return The nfsGroupId.
     */
    public java.lang.String getNfsGroupId() {
      java.lang.Object ref = nfsGroupId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nfsGroupId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string nfsGroupId = 4;</code>
     * @return The bytes for nfsGroupId.
     */
    public com.google.protobuf.ByteString
        getNfsGroupIdBytes() {
      java.lang.Object ref = nfsGroupId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nfsGroupId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string nfsGroupId = 4;</code>
     * @param value The nfsGroupId to set.
     * @return This builder for chaining.
     */
    public Builder setNfsGroupId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      nfsGroupId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string nfsGroupId = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearNfsGroupId() {
      
      nfsGroupId_ = getDefaultInstance().getNfsGroupId();
      onChanged();
      return this;
    }
    /**
     * <code>string nfsGroupId = 4;</code>
     * @param value The bytes for nfsGroupId to set.
     * @return This builder for chaining.
     */
    public Builder setNfsGroupIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      nfsGroupId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object filePermission_ = "";
    /**
     * <code>string filePermission = 5;</code>
     * @return The filePermission.
     */
    public java.lang.String getFilePermission() {
      java.lang.Object ref = filePermission_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        filePermission_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string filePermission = 5;</code>
     * @return The bytes for filePermission.
     */
    public com.google.protobuf.ByteString
        getFilePermissionBytes() {
      java.lang.Object ref = filePermission_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        filePermission_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string filePermission = 5;</code>
     * @param value The filePermission to set.
     * @return This builder for chaining.
     */
    public Builder setFilePermission(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      filePermission_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string filePermission = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearFilePermission() {
      
      filePermission_ = getDefaultInstance().getFilePermission();
      onChanged();
      return this;
    }
    /**
     * <code>string filePermission = 5;</code>
     * @param value The bytes for filePermission to set.
     * @return This builder for chaining.
     */
    public Builder setFilePermissionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      filePermission_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object mTime_ = "";
    /**
     * <code>string mTime = 6;</code>
     * @return The mTime.
     */
    public java.lang.String getMTime() {
      java.lang.Object ref = mTime_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mTime_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string mTime = 6;</code>
     * @return The bytes for mTime.
     */
    public com.google.protobuf.ByteString
        getMTimeBytes() {
      java.lang.Object ref = mTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string mTime = 6;</code>
     * @param value The mTime to set.
     * @return This builder for chaining.
     */
    public Builder setMTime(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      mTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string mTime = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearMTime() {
      
      mTime_ = getDefaultInstance().getMTime();
      onChanged();
      return this;
    }
    /**
     * <code>string mTime = 6;</code>
     * @param value The bytes for mTime to set.
     * @return This builder for chaining.
     */
    public Builder setMTimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      mTime_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object aTIme_ = "";
    /**
     * <code>string aTIme = 7;</code>
     * @return The aTIme.
     */
    public java.lang.String getATIme() {
      java.lang.Object ref = aTIme_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        aTIme_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string aTIme = 7;</code>
     * @return The bytes for aTIme.
     */
    public com.google.protobuf.ByteString
        getATImeBytes() {
      java.lang.Object ref = aTIme_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        aTIme_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string aTIme = 7;</code>
     * @param value The aTIme to set.
     * @return This builder for chaining.
     */
    public Builder setATIme(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      aTIme_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string aTIme = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearATIme() {
      
      aTIme_ = getDefaultInstance().getATIme();
      onChanged();
      return this;
    }
    /**
     * <code>string aTIme = 7;</code>
     * @param value The bytes for aTIme to set.
     * @return This builder for chaining.
     */
    public Builder setATImeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      aTIme_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object fileFormat_ = "";
    /**
     * <code>string FileFormat = 8;</code>
     * @return The fileFormat.
     */
    public java.lang.String getFileFormat() {
      java.lang.Object ref = fileFormat_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fileFormat_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string FileFormat = 8;</code>
     * @return The bytes for fileFormat.
     */
    public com.google.protobuf.ByteString
        getFileFormatBytes() {
      java.lang.Object ref = fileFormat_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fileFormat_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string FileFormat = 8;</code>
     * @param value The fileFormat to set.
     * @return This builder for chaining.
     */
    public Builder setFileFormat(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      fileFormat_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string FileFormat = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearFileFormat() {
      
      fileFormat_ = getDefaultInstance().getFileFormat();
      onChanged();
      return this;
    }
    /**
     * <code>string FileFormat = 8;</code>
     * @param value The bytes for fileFormat to set.
     * @return This builder for chaining.
     */
    public Builder setFileFormatBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      fileFormat_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object creationTime_ = "";
    /**
     * <code>string creationTime = 9;</code>
     * @return The creationTime.
     */
    public java.lang.String getCreationTime() {
      java.lang.Object ref = creationTime_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        creationTime_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string creationTime = 9;</code>
     * @return The bytes for creationTime.
     */
    public com.google.protobuf.ByteString
        getCreationTimeBytes() {
      java.lang.Object ref = creationTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        creationTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string creationTime = 9;</code>
     * @param value The creationTime to set.
     * @return This builder for chaining.
     */
    public Builder setCreationTime(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      creationTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string creationTime = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearCreationTime() {
      
      creationTime_ = getDefaultInstance().getCreationTime();
      onChanged();
      return this;
    }
    /**
     * <code>string creationTime = 9;</code>
     * @param value The bytes for creationTime to set.
     * @return This builder for chaining.
     */
    public Builder setCreationTimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      creationTime_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object auditedOn_ = "";
    /**
     * <code>string auditedOn = 10;</code>
     * @return The auditedOn.
     */
    public java.lang.String getAuditedOn() {
      java.lang.Object ref = auditedOn_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        auditedOn_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string auditedOn = 10;</code>
     * @return The bytes for auditedOn.
     */
    public com.google.protobuf.ByteString
        getAuditedOnBytes() {
      java.lang.Object ref = auditedOn_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        auditedOn_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string auditedOn = 10;</code>
     * @param value The auditedOn to set.
     * @return This builder for chaining.
     */
    public Builder setAuditedOn(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      auditedOn_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string auditedOn = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearAuditedOn() {
      
      auditedOn_ = getDefaultInstance().getAuditedOn();
      onChanged();
      return this;
    }
    /**
     * <code>string auditedOn = 10;</code>
     * @param value The bytes for auditedOn to set.
     * @return This builder for chaining.
     */
    public Builder setAuditedOnBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      auditedOn_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object fileResearchHash_ = "";
    /**
     * <code>string fileResearchHash = 11;</code>
     * @return The fileResearchHash.
     */
    public java.lang.String getFileResearchHash() {
      java.lang.Object ref = fileResearchHash_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fileResearchHash_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string fileResearchHash = 11;</code>
     * @return The bytes for fileResearchHash.
     */
    public com.google.protobuf.ByteString
        getFileResearchHashBytes() {
      java.lang.Object ref = fileResearchHash_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fileResearchHash_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string fileResearchHash = 11;</code>
     * @param value The fileResearchHash to set.
     * @return This builder for chaining.
     */
    public Builder setFileResearchHash(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      fileResearchHash_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string fileResearchHash = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearFileResearchHash() {
      
      fileResearchHash_ = getDefaultInstance().getFileResearchHash();
      onChanged();
      return this;
    }
    /**
     * <code>string fileResearchHash = 11;</code>
     * @param value The bytes for fileResearchHash to set.
     * @return This builder for chaining.
     */
    public Builder setFileResearchHashBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      fileResearchHash_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object currentParty_ = "";
    /**
     * <code>string currentParty = 12;</code>
     * @return The currentParty.
     */
    public java.lang.String getCurrentParty() {
      java.lang.Object ref = currentParty_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        currentParty_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string currentParty = 12;</code>
     * @return The bytes for currentParty.
     */
    public com.google.protobuf.ByteString
        getCurrentPartyBytes() {
      java.lang.Object ref = currentParty_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        currentParty_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string currentParty = 12;</code>
     * @param value The currentParty to set.
     * @return This builder for chaining.
     */
    public Builder setCurrentParty(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      currentParty_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string currentParty = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearCurrentParty() {
      
      currentParty_ = getDefaultInstance().getCurrentParty();
      onChanged();
      return this;
    }
    /**
     * <code>string currentParty = 12;</code>
     * @param value The bytes for currentParty to set.
     * @return This builder for chaining.
     */
    public Builder setCurrentPartyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      currentParty_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:FileDetailsRequest)
  }

  // @@protoc_insertion_point(class_scope:FileDetailsRequest)
  private static final com.grpc.resources.FileDetailsRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.grpc.resources.FileDetailsRequest();
  }

  public static com.grpc.resources.FileDetailsRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FileDetailsRequest>
      PARSER = new com.google.protobuf.AbstractParser<FileDetailsRequest>() {
    @java.lang.Override
    public FileDetailsRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FileDetailsRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FileDetailsRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FileDetailsRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.grpc.resources.FileDetailsRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

