// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fileaudit.proto

package com.grpc.resources;

public final class Fileaudit {
  private Fileaudit() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FileId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FileId_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FileDetailsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FileDetailsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FileDetailsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FileDetailsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017fileaudit.proto\"\"\n\006FileId\022\030\n\020fileResea" +
      "rchHash\030\001 \001(\t\"\213\002\n\022FileDetailsRequest\022\022\n\n" +
      "identifier\030\001 \001(\t\022\027\n\017fileSizeInBytes\030\002 \001(" +
      "\t\022\021\n\tnfsUserId\030\003 \001(\t\022\022\n\nnfsGroupId\030\004 \001(\t" +
      "\022\026\n\016filePermission\030\005 \001(\t\022\r\n\005mTime\030\006 \001(\t\022" +
      "\r\n\005aTIme\030\007 \001(\t\022\022\n\nFileFormat\030\010 \001(\t\022\024\n\014cr" +
      "eationTime\030\t \001(\t\022\021\n\tauditedOn\030\n \001(\t\022\030\n\020f" +
      "ileResearchHash\030\013 \001(\t\022\024\n\014currentParty\030\014 " +
      "\001(\t\"&\n\023FileDetailsResponse\022\017\n\007message\030\001 " +
      "\001(\t2O\n\021FileDetailsInsert\022:\n\013FileDetails\022" +
      "\023.FileDetailsRequest\032\024.FileDetailsRespon" +
      "se\"\0002C\n\020FileDetailsQuery\022/\n\014queryDetails" +
      "\022\007.FileId\032\024.FileDetailsResponse\"\0002N\n\021Upd" +
      "ateFileDetails\0229\n\nupdateFile\022\023.FileDetai" +
      "lsRequest\032\024.FileDetailsResponse\"\0002G\n\020Que" +
      "ryFileHistory\0223\n\020queryFileHistory\022\007.File" +
      "Id\032\024.FileDetailsResponse\"\000B\026\n\022com.grpc.r" +
      "esourcesP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_FileId_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_FileId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FileId_descriptor,
        new java.lang.String[] { "FileResearchHash", });
    internal_static_FileDetailsRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_FileDetailsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FileDetailsRequest_descriptor,
        new java.lang.String[] { "Identifier", "FileSizeInBytes", "NfsUserId", "NfsGroupId", "FilePermission", "MTime", "ATIme", "FileFormat", "CreationTime", "AuditedOn", "FileResearchHash", "CurrentParty", });
    internal_static_FileDetailsResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_FileDetailsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FileDetailsResponse_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
