// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fileaudit.proto

package com.grpc.resources;

public interface FileIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FileId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string fileResearchHash = 1;</code>
   * @return The fileResearchHash.
   */
  java.lang.String getFileResearchHash();
  /**
   * <code>string fileResearchHash = 1;</code>
   * @return The bytes for fileResearchHash.
   */
  com.google.protobuf.ByteString
      getFileResearchHashBytes();
}
