// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fileaudit.proto

package com.grpc.resources;

public interface FileDetailsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FileDetailsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string identifier = 1;</code>
   * @return The identifier.
   */
  java.lang.String getIdentifier();
  /**
   * <code>string identifier = 1;</code>
   * @return The bytes for identifier.
   */
  com.google.protobuf.ByteString
      getIdentifierBytes();

  /**
   * <code>string fileSizeInBytes = 2;</code>
   * @return The fileSizeInBytes.
   */
  java.lang.String getFileSizeInBytes();
  /**
   * <code>string fileSizeInBytes = 2;</code>
   * @return The bytes for fileSizeInBytes.
   */
  com.google.protobuf.ByteString
      getFileSizeInBytesBytes();

  /**
   * <code>string nfsUserId = 3;</code>
   * @return The nfsUserId.
   */
  java.lang.String getNfsUserId();
  /**
   * <code>string nfsUserId = 3;</code>
   * @return The bytes for nfsUserId.
   */
  com.google.protobuf.ByteString
      getNfsUserIdBytes();

  /**
   * <code>string nfsGroupId = 4;</code>
   * @return The nfsGroupId.
   */
  java.lang.String getNfsGroupId();
  /**
   * <code>string nfsGroupId = 4;</code>
   * @return The bytes for nfsGroupId.
   */
  com.google.protobuf.ByteString
      getNfsGroupIdBytes();

  /**
   * <code>string filePermission = 5;</code>
   * @return The filePermission.
   */
  java.lang.String getFilePermission();
  /**
   * <code>string filePermission = 5;</code>
   * @return The bytes for filePermission.
   */
  com.google.protobuf.ByteString
      getFilePermissionBytes();

  /**
   * <code>string mTime = 6;</code>
   * @return The mTime.
   */
  java.lang.String getMTime();
  /**
   * <code>string mTime = 6;</code>
   * @return The bytes for mTime.
   */
  com.google.protobuf.ByteString
      getMTimeBytes();

  /**
   * <code>string aTIme = 7;</code>
   * @return The aTIme.
   */
  java.lang.String getATIme();
  /**
   * <code>string aTIme = 7;</code>
   * @return The bytes for aTIme.
   */
  com.google.protobuf.ByteString
      getATImeBytes();

  /**
   * <code>string FileFormat = 8;</code>
   * @return The fileFormat.
   */
  java.lang.String getFileFormat();
  /**
   * <code>string FileFormat = 8;</code>
   * @return The bytes for fileFormat.
   */
  com.google.protobuf.ByteString
      getFileFormatBytes();

  /**
   * <code>string creationTime = 9;</code>
   * @return The creationTime.
   */
  java.lang.String getCreationTime();
  /**
   * <code>string creationTime = 9;</code>
   * @return The bytes for creationTime.
   */
  com.google.protobuf.ByteString
      getCreationTimeBytes();

  /**
   * <code>string auditedOn = 10;</code>
   * @return The auditedOn.
   */
  java.lang.String getAuditedOn();
  /**
   * <code>string auditedOn = 10;</code>
   * @return The bytes for auditedOn.
   */
  com.google.protobuf.ByteString
      getAuditedOnBytes();

  /**
   * <code>string fileResearchHash = 11;</code>
   * @return The fileResearchHash.
   */
  java.lang.String getFileResearchHash();
  /**
   * <code>string fileResearchHash = 11;</code>
   * @return The bytes for fileResearchHash.
   */
  com.google.protobuf.ByteString
      getFileResearchHashBytes();

  /**
   * <code>string currentParty = 12;</code>
   * @return The currentParty.
   */
  java.lang.String getCurrentParty();
  /**
   * <code>string currentParty = 12;</code>
   * @return The bytes for currentParty.
   */
  com.google.protobuf.ByteString
      getCurrentPartyBytes();
}
